service: neuapp

custom:
  stage: ${opt:stage}

provider:
  name: aws
  runtime: python3.8
  region: ap-southeast-2

resources:
  Resources:
    bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: neuapp-${opt:stage}
